import Head from 'next/head'
import { Layout } from '../components'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

const Home: React.FC = () => {
  return (
    <div>
      <Head>
        <title>iPuc</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout></Layout>
    </div>
  )
}

export default Home
